//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA3.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SanPham
    {
        public int id { get; set; }
        public string name { get; set; }
        public string avatar1 { get; set; }
        public string avatar2 { get; set; }
        public string avatar3 { get; set; }
        public string avatar4 { get; set; }
        public Nullable<int> DanhMucId { get; set; }
        public string ShortDes { get; set; }
        public string FullDes { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceDiscount { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Slug { get; set; }
        public Nullable<int> ThuongHieuId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload1 { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload2 { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload3 { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload4 { get; set; }
    }
}
